### ISSUE TITLE
Using example Project

### ISSUE THREAD

**Issue by micha1983** [JeremyBYU/modbus#1]
HI,

i'm new to meteor, but not to modbus.
i tried to use your exampple project. what i've to do for get it running?

greetings

Michael

**Comment by JeremyBYU** [comment]
Hey michael! This project is meant for some basic modbus communication for Meteor.  It worked for my purposes and I hope it works for yours. If you really want to use this project, the Readme should help you out.

Basically you need a collection of "tags" that dictates the data you need to write/read from your modbus slave. Then on server startup you configure and call this library to connect to the slave.  This library then repeatidly queries the modbus slaves and updates a "live" database collection of the tags values. 

I would check out the Readme and the tests to learn more about how to use it!
Hope this helps.

**Comment by micha1983** [comment]
Hi,
Thanks for your Feedback. 
I've implemented it. And it's working quite nice. 
I'm jpg shure if it's working with to different Slave Adresses at the Same Time. 
Can you give me here a Feedback?
Maybe i Have to Change the config to an array and das a prefix for each plc. 

Thanks for your answer.

**Comment by JeremyBYU** [comment]
Hey sorry I didnt get back you soon. I believe that my implementation only allowed one slave address.  Sorry!
